<a href="https://colab.research.google.com/github/priyasubha4/Python/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello World")

Hello World


In [3]:
3>5
7<20


True

In [4]:
3+5

8

In [5]:
8-15

-7

In [6]:
5<80

True

In [7]:
8>2

True

In [8]:
13*15

195

In [9]:
30/2

15.0

In [10]:
round(15.0,0)

15.0

In [11]:
20==30

False

In [12]:
20==20

True

In [13]:
round(20.12,1)

20.1

In [14]:
20!=10

True

In [15]:
10<=10

True

In [16]:
15.02>=15

True

In [18]:
i=0
whilei<=10:
print(i)
i=i+1

SyntaxError: ignored

In [19]:
i=0
while i<=10:
  print(i)
  i=i+1
  

0
1
2
3
4
5
6
7
8
9
10


In [20]:
i=0
while i<=10:
  print(i)
  i=i+1
print("End loops")

0
1
2
3
4
5
6
7
8
9
10
End loops


In [21]:
i=10
while i<=10:
  print(i)
  i=i+1
print("End loops")

10
End loops


In [22]:
for i in range(5):
  print("Hi Ammu")

Hi Ammu
Hi Ammu
Hi Ammu
Hi Ammu
Hi Ammu


In [23]:
import numpy as np

In [24]:
from numpy.random import randn


In [33]:
result = None
x=randn()
if x>1:
  result = "Greater than 1"
print(x)
print(result)

-0.3439162563794927
None


In [35]:
x=randn()
if x>1:
  result = "Greater than 1"
  else:
    result = "less than 1"
print(x)
print(result)

SyntaxError: ignored

In [36]:
# Creating a List
list1 =[1,2,3,4, 'abc', 'Good', True, 20.36]
type(list1)

list

In [37]:
# using functions

In [38]:
range (10,30)

range(10, 30)

In [42]:
list (range(10,30))

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [43]:
Hilist = list(range(10,30))

In [44]:
print(Hilist)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [45]:
len(Hilist)

20

In [46]:
type(Hilist)

list

In [47]:
max(Hilist)

29

In [48]:
min(Hilist)

10

In [50]:
P = np.array[(2356, 1254, 2589, 9874, 6541, 3654, 7856)]

TypeError: ignored

In [51]:
import numpy as ap

In [54]:
a = np.array ([2356, 1254, 2589, 9874, 6541, 3654, 7856])

In [55]:
a.mean()

4874.857142857143

In [56]:
a

array([2356, 1254, 2589, 9874, 6541, 3654, 7856])

In [57]:
a[::3]

array([2356, 9874, 7856])

In [58]:
a[3:5]

array([9874, 6541])

In [66]:
c = a [2:5]

In [62]:
c

array([2589, 9874])

In [63]:
c[:]

array([2589, 9874])

In [64]:
a


array([2356, 1254, 2589, 9874, 6541, 3654, 7856])

In [65]:
c

array([2589, 9874])